name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore src/FluentGuards/FluentGuards
    - name: Build
      run: dotnet build src/FluentGuards/FluentGuards --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/FluentGuards.UnitTests --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack src/FluentGuards/FluentGuards --configuration Release --no-restore
